### PR TITLE
Fix IE clipboard support by using a polyfill lib

### PR DESCRIPTION
**Pull request by partynikko**
Created due to issue #84

_Clipboard API has been replaced by a clipboard
library to support IE while maintaining the same
behaviour. The copy/paste actions are looked for
on key down. Also adds babel-polyfill to ensure
Promises and other stuff work as expected._

Do you find this solution applicable? I know the Clipboard API is great but unfortunately lacks support for IE which seems to be sought out for.

I haven't fixed the Datasheet tests yet as I would first like to hear what you think about the solution.

Best regards

### CODE REVIEW

**Comment by nadbm** [comment]
I like this a lot, this is the most minimal change I've seen to support IE so the PR is definitely welcome.
Thanks @nikkop

**Comment by nikkop** [comment]
@nadbm Nice to hear, glad you want to accept it 👍 

Would you mind fixing the failing tests? Unfortunately it's beyond my skills.

Best regards

**Comment by ankerek** [comment]
Hi @nadbm, any progress here?

**Comment by pololitr** [comment]
Hey @nadbm it would be a huge help if this PR would be merged. It also fixes issues with IE for me. Are you planing on margin it? Thanks!! :) 
👍

**Comment by nadbm** [comment]
@ankerek @pololitr I do plan on merging this by next week. I didn't get a chance to update the tests. Feel free to use this branch for now.

**Comment by ankerek** [comment]
Hi @nadbm, any update here?

**Comment by nadbm** [comment]
@ankerek  Unfortunately, I am unable to update the current test suite using the clipboard polyfill. The api's used on the polyfill are not readily available on JSDOM. I will look

**Comment by nikkop** [comment]
@nadbm We believe in you! Can't wait for it to be merged 😄

**Comment by tmreay** [comment]
Is there any status about getting these tests passing?

**Comment by nadbm** [comment]
Unfortunately, current tests are done using JSDOM, and that does not support the APIs given by clipboard-polyfill

https://github.com/jsdom/jsdom/issues/1742
https://github.com/jsdom/jsdom/issues/1568

I am keeping this PR open for anyone trying to use this on IE. Im not actively working on this project so if there are PRs that would fix these tests, I will merge them.

**Comment by nadbm** [comment]
Merged PR #162

**Pull request closed without merging**
