### PR TITLE
Parameterize rendering to allow for easier customization

### PR DESCRIPTION
**Pull request by patrick-jones**
At long last, my PR to address #26. I apologize for disappearing so long; I was really under the gun at work and could not give this the attention it deserved. But on the plus side I've had a few months to use and refine this code in a real application.

This PR is not really as big as it looks. A lot of the changes are just moving code around so it is easier to parameterize. Here's a quick guide to what changes I made and why:

#### Extract rendering code
The code for displaying all of the major elements (sheet, row, cell, viewer, editor) is factored out of `DataSheet` and `DataCell`.  Those two classes now manage state and overall structure, but do not control the actual generated markup. This makes it easy to customize things on a fairly granular level.

#### Refactoring keyboard handling
I moved some of the keyboard event handling from `DataSheet` to `DataCell`, and changed it to use the react event system rather than native browser events. I did this because the previous implementation tended to interfere with my custom editors. For example, an Enter keystroke that I needed to handle within my custom editor would be stolen by the DataSheet and switch me out of edit mode. This is a [known feature](https://github.com/facebook/react/issues/7094) of the react synthetic event system. To solve this I pushed keyboard handling in edit mode down into the cell and made it accessible to editors, and gave editors explicit properties to commit and revert editing.

You will notice two spots where I use `setTimeout` in event handling code. It's not my favorite solution, but I needed a way to make sure that native events would not run before react events had the chance to be processed.

### CODE REVIEW

**Comment by nadbm** [comment]
Thanks for the pull request @patrick-jones ! 
Just to be sure, is the api backwards compatible ?
I'll review it soon.

**Comment by patrick-jones** [comment]
Yes, it is backwards compatible.

**Comment by Sediug** [comment]
Looks great ^^ I think it just need a few test cases and that will be great. I'm working myself in some extra features and refactoring the code structure. I like the approach of code separation in more small components.

**Comment by nadbm** [comment]
hey @patrick-jones , 
I'm reviewing this and it's fantastic but Im facing an issue: 
Reproduce this way: 
1) Go to a cell and start editing and type
2) Press TAB 
3) You are blocked at this point, the focus switched to an outside element
I'll look into this further but you may have a quick solution

**Comment by patrick-jones** [comment]
I'll try to have a look this evening. I assume this is in the example page?

**Comment by nadbm** [comment]
It's cool @patrick-jones , it was a simple enough fix. I'll merge this later in the evening in a separate branch, if you can review that a little bit it would be great

**Comment by nadbm** [comment]
Merged it, @patrick-jones 
Please try out and let me know if I missed any bugs. 
I refactored the code a bit before merging, it was primarily combining the keyboard movements from the datacell and datasheet. Some movement were being repeated (left/right..etc)
+ Added a test for handleComponentKey 
@Sediug

**Comment by patrick-jones** [comment]
I'v eincorporated the latest into my project and everything seems good to me.

**Pull request merged**
