### PR TITLE
Adds arguments for cell coordinates to `valueRenderer` and `dataRenderer`

### LINKED ISSUE #20: Include row and column in valueRenderer and dataRenderer
It would be useful to include row and column indices as arguments to the `valueRenderer` and `dataRenderer` callbacks. That would make it easy to make a model to say (for example), "column 3 is formatted as Chinese yuan". The revised signature would be `valueRenderer(cell, row, col) => string`

### PR DESCRIPTION
**Pull request by patrick-jones**
Added cell coordinates to callbacks and added note to documentation.

Closes #20

### CODE REVIEW

**Comment by nadbm** [comment]
@patrick-jones There's onCopy method that also uses valueRenderer and dataRenderer. So they would need to be passed the columns. I can add that over the weekend. I'll merge it after. Thanks for the PR

**Comment by patrick-jones** [comment]
Ah, missed that one

**Comment by patrick-jones** [comment]
I added a commit to fix this oversight. I can squash them into one if you prefer.

**Comment by nadbm** [comment]
no need, this is  great @patrick-jones, thanks!

**Pull request merged**
