### PR TITLE
 Add condition to replace onDoubleClick with onClick to make it work for mobile.

### PR DESCRIPTION
**Pull request by sherbakov1**

### CODE REVIEW

**Comment by sherbakov1** [comment]
Any chance that it can be approved? It would be nice to replace onDblClick with onClick for mobile devices.

**Comment by nadbm** [comment]
Hey @sherbakov1, just quickly looked over this. 
First I haven't built this for mobile as there are lot of edge cases. However this solution seems to forward the onDoubleClick (meant to start edit) into a onClick (meant to start a selection).
If your goal is to only start edit on touch, can I suggest trying ```ontouchstart``` to see if that works? This would also remove the helper code to detect mobile

**Comment by nadbm** [comment]
Just did a quick test: ```onTouchEnd={onDoubleClick}```  is sufficient for what you're trying to achieve. Feel free to just add that and I'll merge.

**Comment by sherbakov1** [comment]
@nadbm thank you for the fast response and your help. I just pushed these changes.

**Pull request merged**
