### PR TITLE
Adds "editing" class to cell during cell edit

### PR DESCRIPTION
**Pull request by syabro**

### CODE REVIEW

**Comment by nadbm** [comment]
@syabro Can you describe why you need this? 
Currently the editing styles are inline, and this feels redundant.

**Comment by syabro** [comment]
@nadbm because I want to add a padding only to cell that is not in editable state.

What do you mean "editing styles are inline"

**Comment by nadbm** [comment]
I see that makes sense, can you fix the test as well?

**Comment by syabro** [comment]
@nadbm of course — will do tomorrow

**Comment by syabro** [comment]
@nadbm done

**Comment by nadbm** [comment]
great thanks!

**Comment by syabro** [comment]
@nadbm could you also please release a new version?

**Pull request merged**
