### PR TITLE
Typescript definitions

### PR DESCRIPTION
**Pull request by astegmaier**
I created what I believe to be a complete `d.ts` file based on the documentation (in response to issue #70). I've tested it in the context of a personal typescript project that exercises all the documented functionality of the package.

I also added a section to the readme to get people started. I'm open to input here about the best way to organize this, since it's probably only relevant to some people.

Please let me know if you have any feedback, and if there's anything I should add or change. Thanks!

### CODE REVIEW

**Comment by astegmaier** [comment]
@weswigham - I'd love your feedback about the way I did generic inheritance. I was mostly imitating what you had started, but I made some tweaks and improvements. Is this the best approach, given the current state of typescript, or can I do better?

**Comment by weswigham** [comment]
I'd include an example of using it generically with an SFC, but otherwise seems good.

**Comment by astegmaier** [comment]
I went ahead and added an example of using an SFC component as a CellRenderer (I think that was what you were suggesting?). But the coveralls job seems to have stalled (it started 16 hours ago). @nadbm - do you have a way of restarting it? Assuming it passes like before, are there any other changes you'd like me to make, or is it ready to merge?

**Comment by weswigham** [comment]
> I went ahead and added an example of using an SFC component as a CellRenderer

That's probably helpful! But I meant something along the lines of

```ts
const MyParameterizedDatasheet = <TCell>(props: { grid: {value: TCell}[][] }) => <ReactDataSheet data={props.grid} valueRenderer={(cell) => cell.value} />

React.render("id", <MyApp>
  <MyParameterizedDatasheet grid={[[{value: 1}, {value: -3}],[{value: -2}, {value: 4}]]} />
</MyApp>)
```

Where the base `ReactDataSheet` class is used within the definition of a generic SFC.

**Comment by nadbm** [comment]
Thanks for the great PR @astegmaier

Typescript is fairly foreign to me so give me some time to properly review this. As for coveralls, I’m not too certain why it’s not picking up the change, I’ll try to initiate it manually.

**Comment by astegmaier** [comment]
@weswigham - I tried playing around to get your example working, but no luck so far. It might be my ignorance about the intricacies of SFCs and TypeScript, or maybe it's a mistake in my definitions that's thwarting it from working. If you have a chance, could you give it a shot in real code with my definitions as a starting point? If you think this is a useful pattern, I'd love to support it.

**Comment by nadbm** [comment]
Hey @astegmaier just got around to merging this. I also added some types that were added through a pull request previously. Let me know what you think. This is effectively my first typescript code so just being sure! 😅

**Comment by astegmaier** [comment]
Thanks for accepting this! The modifications you made look good, but I had one minor suggestion.

**Comment by nadbm** [comment]
Hey @astegmaier might have missed a message, what is the suggestion?

**Comment by astegmaier** [comment]
Oh sorry the comment was [here](https://github.com/nadbm/react-datasheet/commit/c481bc4b1056aa59fcbd23c57c52f826d8cbf9ee). It's probably not a big deal either way.

**Comment by nadbm** [comment]
Oh thanks, yes I will get to that on the next release. The change is more to the code than the typescript interface itself. Cheers !

**Comment by ririvas** [comment]
@astegmaier, I had a question regarding the types and you seem like primary author. For generic portion, why do types extend themselves? 

For example:
`interface DataSheetProps<T extends Cell<T, V>, V> {   
cellRenderer?: CellRenderer<T, V>  
}`

As opposed to 
`interface DataSheetProps<T, V> {   
  cellRenderer?: CellRenderer<Cell<T, V>, V>   
}`

The current type definitions work fine for me. Just a bit curious on the implementation detail

**Comment by astegmaier** [comment]
@ririvas - sorry I wrote those a while ago so I might have this off a bit, but looking at it fresh, it looks like:

- `Cell` has certain special predefined props (e.g. `ValueViewer` and `dataEditor`) whose type depends on the precise type of Cell. 
- But `Cell` itself can potentially be extended by the user with additional props, and you want `ValueViewer` and `dataEditor` to be aware of this extension. This is what `T` is - and why it is constrained to always be an extension of `Cell`, not just anything.

Does that make sense?

**Comment by ririvas** [comment]
@astegmaier Thank you for pointing out the special predefined props. I did not catch that circular reference. That makes sense now.

**Pull request merged**
