### PR TITLE
suppress warning for unsafe lifecylce method

### PR DESCRIPTION
**Pull request by Flaneder**
relates to #146, but is not fixing it properly.

### CODE REVIEW

**Comment by Flaneder** [comment]
> /home/travis/build/nadbm/react-datasheet/src/DataCell.js:41:3: Identifier 'UNSAFE_componentWillReceiveProps' is not in camel case.

There is no way to rename this function.
Is there a way to make an exception here?

**Comment by srgraham** [comment]
on the line before it add `// eslint-disable-next-line camelcase` and it should be ignored

**Comment by Flaneder** [comment]
So it seems like tests are failing (after ignoring the linting error above), because `react-datasheet` tests are runing with `react v15.0.0`. `UNSAFE` lifecycle hooks where introduced in `react v16.x`.

This means `UNSAFE_componentWillReceiveProps` will never be called and test are obviously failing.
The would also break support for `react v15.x`, wouldn't it?

What's the best way to proceed here?

**Comment by nadbm** [comment]
thank you for the PR @Flaneder, I haven't had the time to dedicate to this project. I will upgrade React the react version today and hopefully remove the error

**Comment by nadbm** [comment]
Fixed here https://github.com/nadbm/react-datasheet/pull/178

**Pull request closed without merging**
