### PR TITLE
Adds options to control cell width and text overflow

### LINKED ISSUE #7: text overflow?
Not gonna call the current behavior a "bug" but i figure a thread on what should be done for overflow is a worthwhile discussion. 

Current Behavior: 
react_datasheet_component

Google sheets:
untitled_spreadsheet_-_google_sheets_and_terminal_ _-bash_ _182x58

Does it makes sense to truncate (overflow hidden) when the next cell is filled, but not when empty? What if it is going to overlap a a third cell that is filled... do we allow overflow into the second empty cell then hide when reaching the third?

### LINKED ISSUE #25: Column widths
It would be useful to be able to specify column widths. These could be applied using a `style` attribute when rendering the cells. I can do a PR for this.

### LINKED ISSUE #27: Text-Overflow
If the text is too long in two adjacent cell, the text will overlay each other and hard to distinct.
Is there a way to support text-overflow?
I have tried text-overflow to <span> but it seems not working.

### PR DESCRIPTION
**Pull request by patrick-jones**
Adds ability to set cell widths and specify how to handle text overflow (wrap, don't wrap allow overflow, clip overflow).

Resolves #25, Resolves #7, resolves #27

### CODE REVIEW

**Comment by nadbm** [comment]
Thanks @patrick-jones. Just wondering, wouldn't it be simpler to have a "style" attribute on each cell instead of just width?

**Comment by patrick-jones** [comment]
It may be a matter of taste, but I think surfacing a common option like width as a property makes for a friendlier API. I can see using a raw style tag to change relatively obscure properties, but width is a very first-class property in a grid. Certainly most grid/spreadsheet like components I've ever worked with offered a direct "width" property.

**Comment by nadbm** [comment]
I do agree with the custom width.
 
How is the width affecting the overall size? Currently the library sets its table style as fixed. So width only changes via colSpan. Doesn't changing a single cell change all the cells together?

**Comment by patrick-jones** [comment]
Well, it does change all the cells in a column, if that's what you mean.  It does not change the other columns. 

But you do bring up an issue I was blind to: the width style doesn't really work if the table is not given an explicit width.  If the table's width isn't set and the column width is too small for the content, the column will just expand. 

I'm not sure if this is really a flaw. After all, that's just the way HTML tables work, and I can't imagine many times when you wouldn't want to set the table width. So maybe it just needs to be documented. What do you think?

**Comment by nadbm** [comment]
I think you mean the reverse. If you have a width set on the table, the columns will be split equally. As long as the width for the table is not set, the cell width property will work. 

I was confusing this myself. I'll just add a comment on the doc for this. And merging this now

**Pull request merged**
