### PR TITLE
Add ability to have a context menu handler on the datasheet

### PR DESCRIPTION
**Pull request by weswigham**
Which is triggered for each cell uniquely.

### CODE REVIEW

**Comment by nadbm** [comment]
@weswigham This is great! Did you have an example usage? Would love to put it on the examples as well :)

**Comment by weswigham** [comment]
Just something like
```
        <ReactDatasheet
            data={fixedData}
            valueRenderer={cell => cell.value}
            onChange={props.onChange}
            onContextMenu={(event, cell, i, j) => {
              toggleRightClickedCell(i, j);
              event.preventDefault();
            }}
        />
```

In my case, I wanted to disable the default right-click menu and toggle the read-onlyness of a cell on right-click.

**Comment by nadbm** [comment]
Are you ever doing anything with the evt object other than preventDefault? 
I would like to keep the api a little consistent so might want change that.

**Comment by weswigham** [comment]
I can see needing the interaction location to spawn a menu at, like is
common in contextmenu handlers.

**Comment by kamaldlk** [comment]
@weswigham do you have any examples for context menu

**Pull request merged**
