### PR TITLE
Adds placeholder option for cell

### PR DESCRIPTION
**Pull request by nearbycoder**
Adds the ability to have placeholder text within the cell. The placeholder text is a span with the `class: placeholder` for external styling options. In addition, I added a test to cover the placeholder case.

### CODE REVIEW

**Comment by nadbm** [comment]
hey @nearbycoder thanks for the pull request. 
However I'd be curious to know the use case. 
The placeholder text can be generated by having cells with the placeholder text and a custom class. Instead of having undefined cells.

Moreover,  the placeholder text cannot change, so why is onChange passing it back

**Comment by nearbycoder** [comment]
@nadbm thanks for the quick response. My thought process was not having to parse out the placeholder values when I want to grab the values from the cells. I am working on building out a graphing application that will turn this data into a CSV file. As for the placeholder onChange that was my misunderstanding, I just needed to spread out the `rowCell` in order to keep the placeholder value on state change.

```
col.map(
  rowCell => {
    return rowCell === cell
      ? { ...rowCell, value: value }
      : rowCell
    }
)
```

**Comment by nadbm** [comment]
@nearbycoder  
Why couldn't you do the following? 
```javascript
valueRenderer={(cell) => cell == null ? "placeholder" : cell.value} 
```

**Comment by nearbycoder** [comment]
@nadbm looks like that works with also adding the additional dataRendered to return an empty string if no value is actually present. Thanks so much for the help, closing this PR as it is unnecessary.
```
dataRenderer={(cell) => cell.value === '' ? '' : cell.value}
valueRenderer={(cell) => cell.value === '' ? cell.placeholder : cell.value}
```

**Pull request closed without merging**
